CC = gcc
INCL = -I/home/guoang/leon/credit_holder -I/home/guoang/leon/include
LIB = -L/home/guoang/leon -L/home/guoang/leon/credit_holder

all: test.c
	$(CC) -g test.c $(INCL) $(LIB) -lcd -lutpm -lkeyutils -o test
